$schema: "https://json-schema.org/draft/2020-12/schema"
description: some
properties:
  gene:
    type: string
    description: name/identifier of gene from which the input reads are amplified
  bam_directory:
    type: string
    description: path (absolute or relative to workflow directory) to a directory containing input BAM files
  SNP_1:
    type: integer
    description: 1-based index of the first SNP in the haplotype
  SNP_2:
    type: integer
    description: 1-based index of the second SNP in the haplotype
  haplotypes:
    type: array
    description: an array containing four strings of two characters each representing the four possible haplotypes, e.g. ["ag", "ac", "gg", "gc"]
  guide:
    type: string
    description: path (absolute or relative to workflow directory) to a FASTA file with a guide sequence used by pbaa to align and cluster reads
  pbaa_options:
    type: array
    description: an array of strings, each of which is an option to pass to pbaa
  slurm_options:
    type: array
    description: an array of strings, each of which is an option to pass to slurm

required:
- gene
- bam_directory
- SNP_1
- SNP_2
- haplotypes
- guide